### ISSUE TITLE
Allow customizing the keybinds

### ISSUE THREAD

**Issue by Dich0tomy** [mikesoylu/ai.vim#1]
Hello,  really nice work.

It would be nice if one could customize the keybinds, `<C-a>` is very often used for incrementation.

I could make a PR if that's too much of a hustle, just let me know.

**Comment by mikesoylu** [comment]
Hey, you can customize like this:


```
" turn off default bindings
let g:ai_no_mappings=1

inoremap <C-l> <Esc>:AI<CR>
nnoremap <C-l> <Esc>:AI 
vnoremap <C-l> :AI 
```
